/* wolfssl options.h
 * repeating the options defined in `wolfssl.vcxproj` for bindgen
 *
 * There are several compile options we have defined in wolfssl.vcxproj, such as
 * WOLFSSL_MIN_RSA_BITS, which are not exported in a form that is consumable by
 * bindgen. In Linux, this file is generated by configure automatically but 
 * unfortunately MsBuild doesn't.
 */

#ifndef WOLFSSL_OPTIONS_H
#define WOLFSSL_OPTIONS_H


#ifdef __cplusplus
extern "C" {
#endif


/**
 * Without this, bindgen will complain about non-safe ffi bindings
 * warning: `extern` block uses type `[i64; 1]`, which is not FFI-safe
     --> .\target\release\build\wolfssl-sys-2e39bffb7e820eea\out/bindings.rs:76864:40
      |
76864 |     pub fn _m_from_float(arg1: f32) -> __m64;
      |                                        ^^^^^ not FFI-safe
      |
      = help: consider passing a pointer to the array
      = note: passing raw arrays by value is not FFI-safe
      = note: `#[warn(improper_ctypes)]` on by default
 */
#undef  HAVE_C___ATOMIC
#define HAVE_C___ATOMIC 1

#undef  WOLFSSL_DTLS_CH_FRAG
#define WOLFSSL_DTLS_CH_FRAG

#undef  HAVE_SECURE_RENEGOTIATION
#define HAVE_SECURE_RENEGOTIATION

#undef  WOLFSSL_MIN_RSA_BITS
#define WOLFSSL_MIN_RSA_BITS 2048

#undef  WOLFSSL_MIN_ECC_BITS
#define WOLFSSL_MIN_ECC_BITS 256

#undef  WOLFSSL_TLS13_MIDDLEBOX_COMPAT
#define WOLFSSL_TLS13_MIDDLEBOX_COMPAT


#ifdef __cplusplus
}
#endif


#endif /* WOLFSSL_OPTIONS_H */

